// Sunflour Bakery — sample menu data for the storefront UI kit.
// Prices in kobo (₦ has no decimals here). Mirrors the printed menu board.
window.SUNFLOUR_MENU = {
  business: {
    name: "Sunflour Bakery",
    tagline: "Made with passion. Served with delight.",
    deliveryBaseFee: 150000,      // ₦1,500
    eveningSurcharge: 50000,      // ₦500 after 6 PM
    bank: { name: "Moniepoint", account: "8123 4567 89", holder: "Sunflour Bakery Ltd" },
    whatsapp: "+234 801 234 5678",
  },
  categories: [
    { slug: "cakes", name: "Cakes" },
    { slug: "burgers", name: "Burgers" },
    { slug: "pizza", name: "Pizza" },
    { slug: "ice-cream", name: "Ice cream" },
    { slug: "pastries", name: "Pastries" },
  ],
  products: [
    { id: "p1", slug: "chocolate-cake", name: "7-inch chocolate cake", category: "cakes",
      price: 1000000, image: "../../assets/food-cake.png", popular: true, status: "ACTIVE",
      desc: "Rich layered sponge with chocolate ganache. Made fresh to order.",
      from: true },
    { id: "p2", slug: "sponge-cake", name: "Sponge cake", category: "cakes",
      price: 200000, image: null, status: "ACTIVE",
      desc: "Light, airy vanilla sponge. A simple everyday favourite." },
    { id: "p3", slug: "beef-burger-special", name: "Beef burger special", category: "burgers",
      price: 300000, image: null, popular: true, status: "ACTIVE",
      desc: "Beef patty, grilled onion, tomato and coleslaw on a soft bun." },
    { id: "p4", slug: "chicken-burger", name: "Chicken burger regular", category: "burgers",
      price: 200000, image: null, status: "ACTIVE",
      desc: "Crispy chicken fillet with fresh trimmings." },
    { id: "p5", slug: "pepperoni-pizza", name: "Pepperoni pizza", category: "pizza",
      price: 750000, image: "../../assets/food-pizza.png", popular: true, status: "ACTIVE",
      desc: "Sauce, cheese, pepperoni. Available small to family size.", from: true },
    { id: "p6", slug: "veggie-pizza", name: "Veggie pizza", category: "pizza",
      price: 550000, image: null, status: "ACTIVE",
      desc: "Sauce, sweet corn, mushroom, onion ring, green pepper, olive.", from: true },
    { id: "p7", slug: "fried-chicken", name: "Peppered fried chicken", category: "pastries",
      price: 350000, image: "../../assets/food-chicken.png", status: "ACTIVE",
      desc: "Golden, spiced and crunchy. Served with dip." },
    { id: "p8", slug: "ice-cream-cone", name: "Ice cream cone", category: "ice-cream",
      price: 250000, image: "../../assets/food-cone.png", status: "ACTIVE",
      desc: "A generous scoop in a crisp waffle cone. Pick your flavour." },
    { id: "p9", slug: "ice-cream-cup", name: "Ice cream cup (3 scoops)", category: "ice-cream",
      price: 450000, image: "../../assets/food-sundae.png", popular: true, status: "ACTIVE",
      desc: "Three scoops with toppings of your choice.", from: true },
    { id: "p10", slug: "meat-pie", name: "Meat pie", category: "pastries",
      price: 120000, image: null, status: "ACTIVE",
      desc: "Flaky pastry with a savoury minced filling." },
    { id: "p11", slug: "jam-doughnut", name: "Jam doughnut", category: "pastries",
      price: 100000, image: null, status: "OUT_OF_STOCK",
      desc: "Soft doughnut with a sweet jam centre." },
    { id: "p12", slug: "swiss-roll", name: "Swiss roll", category: "cakes",
      price: 200000, image: null, status: "ACTIVE",
      desc: "Rolled vanilla sponge with cream." },
  ],
};
